name: Test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with: 
          node-version: 14

      - name: Install Dependencies
        run: yarn install
        
      - name: Test
        run: yarn test --coverage
